// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMvxatKTONkciiUFVpkiCrZwk22voNu8',
    appId: '1:737218311028:web:b66ec7d02811f2730cf221',
    messagingSenderId: '737218311028',
    projectId: 'personal-projekt-aa6b4',
    authDomain: 'personal-projekt-aa6b4.firebaseapp.com',
    databaseURL: 'https://personal-projekt-aa6b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'personal-projekt-aa6b4.firebasestorage.app',
    measurementId: 'G-C8EHXZHLJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUF1IikTYfBp4LCE7pkWEBxliZ8dkik3I',
    appId: '1:737218311028:android:f820e8c0f05831030cf221',
    messagingSenderId: '737218311028',
    projectId: 'personal-projekt-aa6b4',
    databaseURL: 'https://personal-projekt-aa6b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'personal-projekt-aa6b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVDRR3jmy5GKH9RU1FbkOY0AOACXXMLw',
    appId: '1:737218311028:ios:3a1aee523ce373040cf221',
    messagingSenderId: '737218311028',
    projectId: 'personal-projekt-aa6b4',
    databaseURL: 'https://personal-projekt-aa6b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'personal-projekt-aa6b4.firebasestorage.app',
    iosClientId: '737218311028-dbd73kfhl71jogi18kvg5iqnujr39l2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVVDRR3jmy5GKH9RU1FbkOY0AOACXXMLw',
    appId: '1:737218311028:ios:3a1aee523ce373040cf221',
    messagingSenderId: '737218311028',
    projectId: 'personal-projekt-aa6b4',
    databaseURL: 'https://personal-projekt-aa6b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'personal-projekt-aa6b4.firebasestorage.app',
    iosClientId: '737218311028-dbd73kfhl71jogi18kvg5iqnujr39l2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOMvxatKTONkciiUFVpkiCrZwk22voNu8',
    appId: '1:737218311028:web:9268b15b1e81a0eb0cf221',
    messagingSenderId: '737218311028',
    projectId: 'personal-projekt-aa6b4',
    authDomain: 'personal-projekt-aa6b4.firebaseapp.com',
    databaseURL: 'https://personal-projekt-aa6b4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'personal-projekt-aa6b4.firebasestorage.app',
    measurementId: 'G-VJSQTG176J',
  );

}